services:
  account-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${RESOURCES_DB_NAME}
      POSTGRES_USER: ${RESOURCES_DB_USERNAME}
      POSTGRES_PASSWORD: ${RESOURCES_DB_PASSWORD}
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${RESOURCES_DB_USERNAME}", "-d", "${RESOURCES_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env